["nasdaq_symbols"]
symbol = "symbol"
company_name = "company_name"
ETF = "etf"

["other_symbols"]
symbol = "symbol"
company_name = "company_name"
ETF = "etf"

["sp500"]
symbol = "symbol"
Security = "company_name"
# "GICS Sector" = "gics_sector"
# "GICS Sub-Industry" = "gics_sub_industry"
# "Headquarters Location" = "headquarters_location"
# "Date added" = "date_added"
# CIK = "cik"
# Founded = "founded"

["dowjones"]
# Exchange = "exchange"
symbol = "symbol"
Company = "company_name"
# Industry = "industry"
# "Date added" = "date_added"
# Notes = "notes"
# "Index weighting" = "index_weighting"

["indicies"]
symbol = "symbol"
dowjones = "dowjones"
nasdaq100 = "nasdaq100"
sp500 = "sp500"
# Industry = "industry"
# "Date added" = "date_added"
# Notes = "notes"
# "Index weighting" = "index_weighting"

["nasdaq100"]
symbol = "symbol"
company_name = "company_name"
# "Market Cap" = "market_cap"
# "Stock Price" = "stock_price"
# "% Change" = "%_Change"
# Revenue = "Revenue"

["regression_indicators"]
Date = "date"
symbol = "symbol"
CHANNEL_CLOSE_VS_LINE = "CHANNEL_CLOSE_VS_LINE"
CHANNEL_CLOSE_VS_MINUS = "CHANNEL_CLOSE_VS_MINUS"
CHANNEL_CLOSE_VS_PLUS = "CHANNEL_CLOSE_VS_PLUS"
CHANNEL_LOW_VS_LINE = "CHANNEL_LOW_VS_LINE"
CHANNEL_LOW_VS_MINUS = "CHANNEL_LOW_VS_MINUS"
CHANNEL_LOW_VS_PLUS = "CHANNEL_LOW_VS_PLUS"
CHANNEL_HIGH_VS_LINE = "CHANNEL_HIGH_VS_LINE"
CHANNEL_HIGH_VS_MINUS = "CHANNEL_HIGH_VS_MINUS"
CHANNEL_HIGH_VS_PLUS = "CHANNEL_HIGH_VS_PLUS"

["regression_indicators_ma"]
Date = "date"
symbol = "symbol"
CHANNEL_CLOSE_VS_MINUS_MA5 = "CHANNEL_CLOSE_VS_MINUS_MA5"
CHANNEL_CLOSE_VS_MINUS_MA10 = "CHANNEL_CLOSE_VS_MINUS_MA10"
CHANNEL_CLOSE_VS_MINUS_MA15 = "CHANNEL_CLOSE_VS_MINUS_MA15"
CHANNEL_CLOSE_VS_LINE_MA5 = "CHANNEL_CLOSE_VS_LINE_MA5"
CHANNEL_CLOSE_VS_LINE_MA10 = "CHANNEL_CLOSE_VS_LINE_MA10"
CHANNEL_CLOSE_VS_LINE_MA15 = "CHANNEL_CLOSE_VS_LINE_MA15"
CHANNEL_CLOSE_VS_PLUS_MA5 = "CHANNEL_CLOSE_VS_PLUS_MA5"
CHANNEL_CLOSE_VS_PLUS_MA10 = "CHANNEL_CLOSE_VS_PLUS_MA10"
CHANNEL_CLOSE_VS_PLUS_MA15 = "CHANNEL_CLOSE_VS_PLUS_MA15"


["ma_future"]
Date = "date"
symbol = "symbol"
FUTURE_END_CLOSE_5 = "FUTURE_END_CLOSE_5"
FUTURE_END_CLOSE_10 = "FUTURE_END_CLOSE_10"
FUTURE_END_CLOSE_15 = "FUTURE_END_CLOSE_15"
FUTURE_END_CLOSE_20 = "FUTURE_END_CLOSE_20"
FUTURE_END_CLOSE_30 = "FUTURE_END_CLOSE_30"
FUTURE_END_CLOSE_50 = "FUTURE_END_CLOSE_50"
FUTURE_MAX_CLOSE_5 = "FUTURE_MAX_CLOSE_5"
FUTURE_MAX_CLOSE_10 = "FUTURE_MAX_CLOSE_10"
FUTURE_MAX_CLOSE_15 = "FUTURE_MAX_CLOSE_15"
FUTURE_MAX_CLOSE_20 = "FUTURE_MAX_CLOSE_20"
FUTURE_MAX_CLOSE_30 = "FUTURE_MAX_CLOSE_30"
FUTURE_MAX_CLOSE_50 = "FUTURE_MAX_CLOSE_50"
FUTURE_MAX_HIGH_5 = "FUTURE_MAX_HIGH_5"
FUTURE_MAX_HIGH_10 = "FUTURE_MAX_HIGH_10"
FUTURE_MAX_HIGH_15 = "FUTURE_MAX_HIGH_15"
FUTURE_MAX_HIGH_20 = "FUTURE_MAX_HIGH_20"
FUTURE_MAX_HIGH_30 = "FUTURE_MAX_HIGH_30"
FUTURE_MAX_HIGH_50 = "FUTURE_MAX_HIGH_50"

["ta__change"]
Date = "date"
symbol = "symbol"
CHANGE_CLOSE_5 = "CHANGE_CLOSE_5"
CHANGE_CLOSE_10 = "CHANGE_CLOSE_10"
CHANGE_CLOSE_20 = "CHANGE_CLOSE_20"
CHANGE_CLOSE_30 = "CHANGE_CLOSE_30"
CHANGE_CLOSE_50 = "CHANGE_CLOSE_50"
CHANGE_CLOSE_100 = "CHANGE_CLOSE_100"
CHANGE_CLOSE_200 = "CHANGE_CLOSE_200"

["ta__ma_ratio"]
Date = "date"
symbol = "symbol"
SMA_RATIO_14_30 = "SMA_RATIO_14_30"
SMA_RATIO_14_50 = "SMA_RATIO_14_50"
SMA_RATIO_14_100 = "SMA_RATIO_14_100"
SMA_RATIO_14_200 = "SMA_RATIO_14_200"
SMA_RATIO_30_50 = "SMA_RATIO_30_50"
SMA_RATIO_30_100 = "SMA_RATIO_30_100"
SMA_RATIO_30_200 = "SMA_RATIO_30_200"
SMA_RATIO_50_100 = "SMA_RATIO_50_100"
SMA_RATIO_50_200 = "SMA_RATIO_50_200"
SMA_RATIO_100_200 = "SMA_RATIO_100_200"
EMA_RATIO_14_30 = "EMA_RATIO_14_30"
EMA_RATIO_14_50 = "EMA_RATIO_14_50"
EMA_RATIO_14_100 = "EMA_RATIO_14_100"
EMA_RATIO_14_200 = "EMA_RATIO_14_200"
EMA_RATIO_30_50 = "EMA_RATIO_30_50"
EMA_RATIO_30_100 = "EMA_RATIO_30_100"
EMA_RATIO_30_200 = "EMA_RATIO_30_200"
EMA_RATIO_50_100 = "EMA_RATIO_50_100"
EMA_RATIO_50_200 = "EMA_RATIO_50_200"
EMA_RATIO_100_200 = "EMA_RATIO_100_200"

["ta__talib"]
Date = "date"
symbol = "symbol"
HT_DCPERIOD = "HT_DCPERIOD"
HT_DCPHASE = "HT_DCPHASE"
HT_PHASOR___1 = "HT_PHASOR___1"
HT_PHASOR___2 = "HT_PHASOR___2"
HT_SINE___1 = "HT_SINE___1"
HT_SINE___2 = "HT_SINE___2"
HT_TRENDMODE = "HT_TRENDMODE"
ADX_30 = "ADX_30"
ADXR_30 = "ADXR_30"
APO_12_26_0 = "APO_12_26_0"
AROON_30__1 = "AROON_30__1"
AROON_30__2 = "AROON_30__2"
AROONOSC_30 = "AROONOSC_30"
BOP = "BOP"
CCI_30 = "CCI_30"
CMO_30 = "CMO_30"
DX_30 = "DX_30"
MACD_12_26_9__1 = "MACD_12_26_9__1"
MACD_12_26_9__2 = "MACD_12_26_9__2"
MACD_12_26_9__3 = "MACD_12_26_9__3"
MACDEXT_12_0_26_0_9_0__1 = "MACDEXT_12_0_26_0_9_0__1"
MACDEXT_12_0_26_0_9_0__2 = "MACDEXT_12_0_26_0_9_0__2"
MACDEXT_12_0_26_0_9_0__3 = "MACDEXT_12_0_26_0_9_0__3"
MACDFIX_9__1 = "MACDFIX_9__1"
MACDFIX_9__2 = "MACDFIX_9__2"
MACDFIX_9__3 = "MACDFIX_9__3"
MFI_30 = "MFI_30"
MINUS_DI_30 = "MINUS_DI_30"
MINUS_DM_30 = "MINUS_DM_30"
MOM_30 = "MOM_30"
PLUS_DI_30 = "PLUS_DI_30"
PLUS_DM_30 = "PLUS_DM_30"
PPO_12_26_0 = "PPO_12_26_0"
ROC_30 = "ROC_30"
ROCP_30 = "ROCP_30"
ROCR_30 = "ROCR_30"
ROCR100_30 = "ROCR100_30"
RSI_14 = "RSI_14"
RSI_30 = "RSI_30"
STOCH_5_3_0_26_0__1 = "STOCH_5_3_0_26_0__1"
STOCH_5_3_0_26_0__2 = "STOCH_5_3_0_26_0__2"
STOCHF_5_3_0__1 = "STOCHF_5_3_0__1"
STOCHF_5_3_0__2 = "STOCHF_5_3_0__2"
STOCHRSI_30_5_3_0__1 = "STOCHRSI_30_5_3_0__1"
STOCHRSI_30_5_3_0__2 = "STOCHRSI_30_5_3_0__2"
TRIX_30 = "TRIX_30"
ULTOSC_7_14_28 = "ULTOSC_7_14_28"
WILLR_30 = "WILLR_30"
BBANDS_30_2_2_0__1 = "BBANDS_30_2_2_0__1"
BBANDS_30_2_2_0__2 = "BBANDS_30_2_2_0__2"
BBANDS_30_2_2_0__3 = "BBANDS_30_2_2_0__3"
DEMA_30 = "DEMA_30"
EMA_14 = "EMA_14"
EMA_30 = "EMA_30"
EMA_50 = "EMA_50"
EMA_100 = "EMA_100"
EMA_200 = "EMA_200"
HT_TRENDLINE = "HT_TRENDLINE"
KAMA_30 = "KAMA_30"
MIDPOINT_30 = "MIDPOINT_30"
MIDPRICE_30 = "MIDPRICE_30"
SAR_0_0 = "SAR_0_0"
SAREXT_0_0_0_0_0_0_0_0 = "SAREXT_0_0_0_0_0_0_0_0"
SMA_14 = "SMA_14"
SMA_30 = "SMA_30"
SMA_50 = "SMA_50"
SMA_100 = "SMA_100"
SMA_200 = "SMA_200"
T3_30_0 = "T3_30_0"
TEMA_30 = "TEMA_30"
TRIMA_30 = "TRIMA_30"
WMA_14 = "WMA_14"
WMA_30 = "WMA_30"
WMA_50 = "WMA_50"
WMA_100 = "WMA_100"
WMA_200 = "WMA_200"
CDL2CROWS = "CDL2CROWS"
CDL3BLACKCROWS = "CDL3BLACKCROWS"
CDL3INSIDE = "CDL3INSIDE"
CDL3LINESTRIKE = "CDL3LINESTRIKE"
CDL3OUTSIDE = "CDL3OUTSIDE"
CDL3STARSINSOUTH = "CDL3STARSINSOUTH"
CDL3WHITESOLDIERS = "CDL3WHITESOLDIERS"
CDLABANDONEDBABY_0 = "CDLABANDONEDBABY_0"
CDLADVANCEBLOCK = "CDLADVANCEBLOCK"
CDLBELTHOLD = "CDLBELTHOLD"
CDLBREAKAWAY = "CDLBREAKAWAY"
CDLCLOSINGMARUBOZU = "CDLCLOSINGMARUBOZU"
CDLCONCEALBABYSWALL = "CDLCONCEALBABYSWALL"
CDLCOUNTERATTACK = "CDLCOUNTERATTACK"
CDLDARKCLOUDCOVER_0 = "CDLDARKCLOUDCOVER_0"
CDLDOJI = "CDLDOJI"
CDLDOJISTAR = "CDLDOJISTAR"
CDLDRAGONFLYDOJI = "CDLDRAGONFLYDOJI"
CDLENGULFING = "CDLENGULFING"
CDLEVENINGDOJISTAR_0 = "CDLEVENINGDOJISTAR_0"
CDLEVENINGSTAR_0 = "CDLEVENINGSTAR_0"
CDLGAPSIDESIDEWHITE = "CDLGAPSIDESIDEWHITE"
CDLGRAVESTONEDOJI = "CDLGRAVESTONEDOJI"
CDLHAMMER = "CDLHAMMER"
CDLHANGINGMAN = "CDLHANGINGMAN"
CDLHARAMI = "CDLHARAMI"
CDLHARAMICROSS = "CDLHARAMICROSS"
CDLHIGHWAVE = "CDLHIGHWAVE"
CDLHIKKAKE = "CDLHIKKAKE"
CDLHIKKAKEMOD = "CDLHIKKAKEMOD"
CDLHOMINGPIGEON = "CDLHOMINGPIGEON"
CDLIDENTICAL3CROWS = "CDLIDENTICAL3CROWS"
CDLINNECK = "CDLINNECK"
CDLINVERTEDHAMMER = "CDLINVERTEDHAMMER"
CDLKICKING = "CDLKICKING"
CDLKICKINGBYLENGTH = "CDLKICKINGBYLENGTH"
CDLLADDERBOTTOM = "CDLLADDERBOTTOM"
CDLLONGLEGGEDDOJI = "CDLLONGLEGGEDDOJI"
CDLLONGLINE = "CDLLONGLINE"
CDLMARUBOZU = "CDLMARUBOZU"
CDLMATCHINGLOW = "CDLMATCHINGLOW"
CDLMATHOLD_0 = "CDLMATHOLD_0"
CDLMORNINGDOJISTAR_0 = "CDLMORNINGDOJISTAR_0"
CDLMORNINGSTAR_0 = "CDLMORNINGSTAR_0"
CDLONNECK = "CDLONNECK"
CDLPIERCING = "CDLPIERCING"
CDLRICKSHAWMAN = "CDLRICKSHAWMAN"
CDLRISEFALL3METHODS = "CDLRISEFALL3METHODS"
CDLSEPARATINGLINES  = "CDLSEPARATINGLINES"
CDLSHOOTINGSTAR  = "CDLSHOOTINGSTAR"
CDLSHORTLINE  = "CDLSHORTLINE"
CDLSPINNINGTOP  = "CDLSPINNINGTOP"
CDLSTALLEDPATTERN  = "CDLSTALLEDPATTERN"
CDLSTICKSANDWICH  = "CDLSTICKSANDWICH"
CDLTAKURI  = "CDLTAKURI"
CDLTASUKIGAP  = "CDLTASUKIGAP"
CDLTHRUSTING  = "CDLTHRUSTING"
CDLTRISTAR  = "CDLTRISTAR"
CDLUNIQUE3RIVER  = "CDLUNIQUE3RIVER"
CDLUPSIDEGAP2CROWS  = "CDLUPSIDEGAP2CROWS"
CDLXSIDEGAP3METHODS  = "CDLXSIDEGAP3METHODS"
AVGPRICE = "AVGPRICE"
MEDPRICE = "MEDPRICE"
TYPPRICE = "TYPPRICE"
WCLPRICE = "WCLPRICE"
LINEARREG_30 = "LINEARREG_30"
LINEARREG_ANGLE_30 = "LINEARREG_ANGLE_30"
LINEARREG_INTERCEPT_30 = "LINEARREG_INTERCEPT_30"
LINEARREG_SLOPE_30 = "LINEARREG_SLOPE_30"
STDDEV_30_1 = "STDDEV_30_1"
TSF_30 = "TSF_30"
VAR_30_1 = "VAR_30_1"
ATR_30 = "ATR_30"
NATR_30 = "NATR_30"
TRANGE = "TRANGE"
AD = "AD"
ADOSC_12_26 = "ADOSC_12_26"
OBV = "OBV"

["regression"]
symbol = "symbol"
max_regression_days = "max_regression_days"
date = "date"
earliest_start_date = "earliest_start_date"
best_regression_date = "best_regression_date"
start = "start"
end = "end"
length = "length"
start_ordinal = "start_ordinal"
end_ordinal = "end_ordinal"
slope = "slope"
intercept = "intercept"
r_value = "r_value"
p_value = "p_value"
std = "std"
stderr = "stderr"
line_start_ordinal_x = "line_start_ordinal_x"
line_end_ordinal_x = "line_end_ordinal_x"
line_start_x = "line_start_x"
line_end_x = "line_end_x"
line_start_y = "line_start_y"
line_end_y = "line_end_y"
line_plus_start_y = "line_plus_start_y"
line_plus_end_y = "line_plus_end_y"
line_minus_start_y = "line_minus_start_y"
line_minus_end_y = "line_minus_end_y"

["price"]
symbol = "symbol"
Date = "date"
Open = "open"
High = "high"
Low = "low"
Close = "close"
Volume = "volume"
Dividends = "dividends"
stock_splits = "stock_splits"

["equity_info"]
symbol = "symbol"
address1 = "address1"
city = "city"
state = "state"
zip = "zip"
country = "country"
website = "website"
industry = "industry"
industryKey = "industry_key"
industryDisp = "industry_disp"
sector = "sector"
sectorKey = "sector_key"
sectorDisp = "sector_disp"
longBusinessSummary = "long_business_summary"
fullTimeEmployees = "full_time_employees"
companyOfficers = "company_officers"
auditRisk = "audit_risk"
boardRisk = "board_risk"
compensationRisk = "compensation_risk"
shareHolderRightsRisk = "share_holder_rights_risk"
overallRisk = "overall_risk"
governanceEpochDate = "governance_epoch_date"
compensationAsOfEpochDate = "compensation_as_of_epoch_date"
irWebsite = "ir_website"
executiveTeam = "executive_team"
maxAge = "max_age"
priceHint = "price_hint"
previousClose = "previous_close"
open = "open"
dayLow = "day_low"
dayHigh = "day_high"
regularMarketPreviousClose = "regular_market_previous_close"
regularMarketOpen = "regular_market_open"
regularMarketDayLow = "regular_market_day_low"
regularMarketDayHigh = "regular_market_day_high"
dividendRate = "dividend_rate"
dividendYield = "dividend_yield"
exDividendDate = "ex_dividend_date"
payoutRatio = "payout_ratio"
fiveYearAvgDividendYield = "five_year_avg_dividend_yield"
beta = "beta"
trailingPE = "trailing_pe"
forwardPE = "forward_pe"
volume = "volume"
regularMarketVolume = "regular_market_volume"
averageVolume = "average_volume"
averageVolume10days = "average_volume10days"
averageDailyVolume10Day = "average_daily_volume10_day"
bid = "bid"
ask = "ask"
bidSize = "bid_size"
askSize = "ask_size"
marketCap = "market_cap"
fiftyTwoWeekLow = "fifty_two_week_low"
fiftyTwoWeekHigh = "fifty_two_week_high"
priceToSalesTrailing12Months = "price_to_sales_trailing12_months"
fiftyDayAverage = "fifty_day_average"
twoHundredDayAverage = "two_hundred_day_average"
trailingAnnualDividendRate = "trailing_annual_dividend_rate"
trailingAnnualDividendYield = "trailing_annual_dividend_yield"
currency = "currency"
tradeable = "tradeable"
enterpriseValue = "enterprise_value"
profitMargins = "profit_margins"
floatShares = "float_shares"
sharesOutstanding = "shares_outstanding"
sharesShort = "shares_short"
sharesShortPriorMonth = "shares_short_prior_month"
sharesShortPreviousMonthDate = "shares_short_previous_month_date"
dateShortInterest = "date_short_interest"
sharesPercentSharesOut = "shares_percent_shares_out"
heldPercentInsiders = "held_percent_insiders"
heldPercentInstitutions = "held_percent_institutions"
shortRatio = "short_ratio"
shortPercentOfFloat = "short_percent_of_float"
impliedSharesOutstanding = "implied_shares_outstanding"
bookValue = "book_value"
priceToBook = "price_to_book"
lastFiscalYearEnd = "last_fiscal_year_end"
nextFiscalYearEnd = "next_fiscal_year_end"
mostRecentQuarter = "most_recent_quarter"
earningsQuarterlyGrowth = "earnings_quarterly_growth"
netIncomeToCommon = "net_income_to_common"
trailingEps = "trailing_eps"
forwardEps = "forward_eps"
lastSplitFactor = "last_split_factor"
lastSplitDate = "last_split_date"
enterpriseToRevenue = "enterprise_to_revenue"
enterpriseToEbitda = "enterprise_to_ebitda"
_52WeekChange = "52_week_change"
SandP52WeekChange = "sand_p52_week_change"
lastDividendValue = "last_dividend_value"
lastDividendDate = "last_dividend_date"
quoteType = "quote_type"
currentPrice = "current_price"
targetHighPrice = "target_high_price"
targetLowPrice = "target_low_price"
targetMeanPrice = "target_mean_price"
targetMedianPrice = "target_median_price"
recommendationMean = "recommendation_mean"
recommendationKey = "recommendation_key"
numberOfAnalystOpinions = "number_of_analyst_opinions"
totalCash = "total_cash"
totalCashPerShare = "total_cash_per_share"
ebitda = "ebitda"
totalDebt = "total_debt"
quickRatio = "quick_ratio"
currentRatio = "current_ratio"
totalRevenue = "total_revenue"
debtToEquity = "debt_to_equity"
revenuePerShare = "revenue_per_share"
returnOnAssets = "return_on_assets"
returnOnEquity = "return_on_equity"
grossProfits = "gross_profits"
freeCashflow = "free_cashflow"
operatingCashflow = "operating_cashflow"
earningsGrowth = "earnings_growth"
revenueGrowth = "revenue_growth"
grossMargins = "gross_margins"
ebitdaMargins = "ebitda_margins"
operatingMargins = "operating_margins"
financialCurrency = "financial_currency"
language = "language"
region = "region"
typeDisp = "type_disp"
quoteSourceName = "quote_source_name"
triggerable = "triggerable"
customPriceAlertConfidence = "custom_price_alert_confidence"
corporateActions = "corporate_actions"
postMarketTime = "post_market_time"
regularMarketTime = "regular_market_time"
exchange = "exchange"
messageBoardId = "message_board_id"
exchangeTimezoneName = "exchange_timezone_name"
exchangeTimezoneShortName = "exchange_timezone_short_name"
gmtOffSetMilliseconds = "gmt_off_set_milliseconds"
market = "market"
esgPopulated = "esg_populated"
shortName = "short_name"
longName = "long_name"
hasPrePostMarketData = "has_pre_post_market_data"
firstTradeDateMilliseconds = "first_trade_date_milliseconds"
postMarketChangePercent = "post_market_change_percent"
postMarketPrice = "post_market_price"
postMarketChange = "post_market_change"
regularMarketChange = "regular_market_change"
regularMarketDayRange = "regular_market_day_range"
fullExchangeName = "full_exchange_name"
averageDailyVolume3Month = "average_daily_volume3_month"
fiftyTwoWeekLowChange = "fifty_two_week_low_change"
fiftyTwoWeekLowChangePercent = "fifty_two_week_low_change_percent"
fiftyTwoWeekRange = "fifty_two_week_range"
fiftyTwoWeekHighChange = "fifty_two_week_high_change"
fiftyTwoWeekHighChangePercent = "fifty_two_week_high_change_percent"
fiftyTwoWeekChangePercent = "fifty_two_week_change_percent"
dividendDate = "dividend_date"
earningsTimestamp = "earnings_timestamp"
earningsTimestampStart = "earnings_timestamp_start"
earningsTimestampEnd = "earnings_timestamp_end"
earningsCallTimestampStart = "earnings_call_timestamp_start"
earningsCallTimestampEnd = "earnings_call_timestamp_end"
isEarningsDateEstimate = "is_earnings_date_estimate"
epsTrailingTwelveMonths = "eps_trailing_twelve_months"
epsForward = "eps_forward"
epsCurrentYear = "eps_current_year"
priceEpsCurrentYear = "price_eps_current_year"
fiftyDayAverageChange = "fifty_day_average_change"
fiftyDayAverageChangePercent = "fifty_day_average_change_percent"
twoHundredDayAverageChange = "two_hundred_day_average_change"
twoHundredDayAverageChangePercent = "two_hundred_day_average_change_percent"
sourceInterval = "source_interval"
exchangeDataDelayedBy = "exchange_data_delayed_by"
averageAnalystRating = "average_analyst_rating"
cryptoTradeable = "crypto_tradeable"
marketState = "market_state"
regularMarketChangePercent = "regular_market_change_percent"
regularMarketPrice = "regular_market_price"
displayName = "display_name"
trailingPegRatio = "trailing_peg_ratio"
# fax = "fax"
# address2 = "address2"
# industrySymbol = "industry_symbol"
# prevName = "prev_name"
# nameChangeDate = "name_change_date"
# ipoExpectedDate = "ipo_expected_date"

["etf_info"]
symbol = "symbol"
longBusinessSummary = "long_business_summary"
companyOfficers = "company_officers"
executiveTeam = "executive_team"
maxAge = "max_age"
priceHint = "price_hint"
previousClose = "previous_close"
open = "open"
dayLow = "day_low"
dayHigh = "day_high"
regularMarketPreviousClose = "regular_market_previous_close"
regularMarketOpen = "regular_market_open"
regularMarketDayLow = "regular_market_day_low"
regularMarketDayHigh = "regular_market_day_high"
trailingPE = "trailing_p_e"
volume = "volume"
regularMarketVolume = "regular_market_volume"
averageVolume = "average_volume"
averageVolume10days = "average_volume10days"
averageDailyVolume10Day = "average_daily_volume10_day"
bid = "bid"
ask = "ask"
bidSize = "bid_size"
askSize = "ask_size"
_yield = "yield"
totalAssets = "total_assets"
fiftyTwoWeekLow = "fifty_two_week_low"
fiftyTwoWeekHigh = "fifty_two_week_high"
fiftyDayAverage = "fifty_day_average"
twoHundredDayAverage = "two_hundred_day_average"
navPrice = "nav_price"
currency = "currency"
tradeable = "tradeable"
category = "category"
ytdReturn = "ytd_return"
beta3Year = "beta3_year"
fundFamily = "fund_family"
fundInceptionDate = "fund_inception_date"
legalType = "legal_type"
quoteType = "quote_type"
language = "language"
region = "region"
typeDisp = "type_disp"
quoteSourceName = "quote_source_name"
triggerable = "triggerable"
customPriceAlertConfidence = "custom_price_alert_confidence"
corporateActions = "corporate_actions"
postMarketTime = "post_market_time"
regularMarketTime = "regular_market_time"
exchange = "exchange"
messageBoardId = "message_board_id"
exchangeTimezoneName = "exchange_timezone_name"
exchangeTimezoneShortName = "exchange_timezone_short_name"
gmtOffSetMilliseconds = "gmt_off_set_milliseconds"
market = "market"
esgPopulated = "esg_populated"
shortName = "short_name"
longName = "long_name"
hasPrePostMarketData = "has_pre_post_market_data"
firstTradeDateMilliseconds = "first_trade_date_milliseconds"
postMarketChangePercent = "post_market_change_percent"
postMarketPrice = "post_market_price"
postMarketChange = "post_market_change"
regularMarketChange = "regular_market_change"
regularMarketDayRange = "regular_market_day_range"
fullExchangeName = "full_exchange_name"
averageDailyVolume3Month = "average_daily_volume3_month"
fiftyTwoWeekLowChange = "fifty_two_week_low_change"
fiftyTwoWeekLowChangePercent = "fifty_two_week_low_change_percent"
fiftyTwoWeekRange = "fifty_two_week_range"
fiftyTwoWeekHighChange = "fifty_two_week_high_change"
fiftyTwoWeekHighChangePercent = "fifty_two_week_high_change_percent"
fiftyTwoWeekChangePercent = "fifty_two_week_change_percent"
dividendYield = "dividend_yield"
trailingThreeMonthReturns = "trailing_three_month_returns"
trailingThreeMonthNavReturns = "trailing_three_month_nav_returns"
netAssets = "net_assets"
epsTrailingTwelveMonths = "eps_trailing_twelve_months"
fiftyDayAverageChange = "fifty_day_average_change"
fiftyDayAverageChangePercent = "fifty_day_average_change_percent"
twoHundredDayAverageChange = "two_hundred_day_average_change"
twoHundredDayAverageChangePercent = "two_hundred_day_average_change_percent"
netExpenseRatio = "net_expense_ratio"
sourceInterval = "source_interval"
exchangeDataDelayedBy = "exchange_data_delayed_by"
cryptoTradeable = "crypto_tradeable"
regularMarketChangePercent = "regular_market_change_percent"
regularMarketPrice = "regular_market_price"
marketState = "market_state"

