from pandera.pandas import DataFrameSchema, Column, Check, Index  # , MultiIndex

indicies_schema = DataFrameSchema(
    columns={
        "symbol": Column(
            dtype="object",
            checks=[
                Check.str_length(
                    min_value=1,
                    max_value=5,
                    raise_warning=True,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "dowjones": Column(
            dtype=bool,
            checks=None,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "nasdaq100": Column(
            dtype=bool,
            checks=None,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "sp500": Column(
            dtype=bool,
            checks=None,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
    },
    checks=None,
    index=Index(
        dtype="int64",
        checks=None,
        nullable=False,
        coerce=True,
        name=None,
        description=None,
        title=None,
    ),
    dtype=None,
    coerce=True,
    strict=False,
    name=None,
    ordered=False,
    unique=None,
    report_duplicates="all",
    unique_column_names=False,
    add_missing_columns=False,
    title=None,
    description=None,
)
