from pandas import Timestamp
from pandera.pandas import DataFrameSchema, Column, Check, Index, MultiIndex

regression_schema = DataFrameSchema(
    columns={
        "symbol": Column(
            dtype="object",
            checks=[
                Check.str_length(
                    min_value=1,
                    max_value=5,
                    raise_warning=True,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "max_regression_days": Column(
            dtype="int64",
            checks=[
                Check.greater_than_or_equal_to(min_value=0, raise_warning=False, ignore_na=True),
                Check.less_than_or_equal_to(max_value=10000, raise_warning=False, ignore_na=True),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "date": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=Timestamp("1900-01-1 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=Timestamp("2030-01-01 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "earliest_start_date": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=Timestamp("1900-01-1 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=Timestamp("2030-01-01 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "best_regression_date": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=Timestamp("1900-01-1 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=Timestamp("2030-01-01 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "start": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=Timestamp("1900-01-1 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=Timestamp("2030-01-01 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "end": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=Timestamp("1900-01-1 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=Timestamp("2030-01-01 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "length": Column(
            dtype="int64",
            checks=[
                Check.greater_than_or_equal_to(min_value=0, raise_warning=False, ignore_na=True),
                Check.less_than_or_equal_to(max_value=10000, raise_warning=False, ignore_na=True),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "start_ordinal": Column(
            dtype="int64",
            checks=[Check.greater_than_or_equal_to(min_value=0, raise_warning=False, ignore_na=True)],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "end_ordinal": Column(
            dtype="int64",
            checks=[Check.greater_than_or_equal_to(min_value=0, raise_warning=False, ignore_na=True)],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "slope": Column(
            dtype="float64",
            checks=None,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "intercept": Column(
            dtype="float64",
            checks=None,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "r_value": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=-1,
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=1,
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "p_value": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=1,
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "std": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "stderr": Column(
            dtype="float64",
            checks=None,
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_start_ordinal_x": Column(
            dtype="int64",
            checks=[Check.greater_than_or_equal_to(min_value=0, raise_warning=False, ignore_na=True)],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_end_ordinal_x": Column(
            dtype="int64",
            checks=[Check.greater_than_or_equal_to(min_value=0, raise_warning=False, ignore_na=True)],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_start_x": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=Timestamp("1900-01-1 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=Timestamp("2030-01-01 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_end_x": Column(
            dtype="datetime64[ns]",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=Timestamp("1900-01-1 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
                Check.less_than_or_equal_to(
                    max_value=Timestamp("2030-01-01 00:00:00"),
                    raise_warning=False,
                    ignore_na=True,
                ),
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_start_y": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_end_y": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_plus_start_y": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_plus_end_y": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_minus_start_y": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
        "line_minus_end_y": Column(
            dtype="float64",
            checks=[
                Check.greater_than_or_equal_to(
                    min_value=0,
                    raise_warning=False,
                    ignore_na=True,
                )
            ],
            nullable=False,
            unique=False,
            coerce=True,
            required=True,
            regex=False,
            description=None,
            title=None,
        ),
    },
    checks=None,
    index=Index(
        dtype="int64",
        checks=None,
        nullable=False,
        coerce=True,
        name=None,
        description=None,
        title=None,
    ),
    dtype=None,
    coerce=True,
    strict=False,
    name=None,
    ordered=False,
    unique=None,
    report_duplicates="all",
    unique_column_names=False,
    add_missing_columns=False,
    title=None,
    description=None,
)
