talib_functions = [
    {"HT_DCPERIOD": {"real": "close"}},
    {"HT_DCPHASE": {"real": "close"}},
    {"HT_PHASOR": {"real": "close"}},
    {"HT_SINE": {"real": "close"}},
    {"HT_TRENDMODE": {"real": "close"}},
    #  {'ACOS': {'real': 'close'}},
    {"ADX": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"ADXR": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"APO": {"real": "close", "fastperiod": 12, "slowperiod": 26, "matype": 0}},
    {"AROON": {"high": "high", "low": "low", "timeperiod": 30}},
    {"AROONOSC": {"high": "high", "low": "low", "timeperiod": 30}},
    {"BOP": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CCI": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"CMO": {"real": "close", "timeperiod": 30}},
    {"DX": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"MACD": {"real": "close", "fastperiod": 12, "slowperiod": 26, "signalperiod": 9}},
    {
        "MACDEXT": {
            "real": "close",
            "fastperiod": 12,
            "fastmatype": 0,
            "slowperiod": 26,
            "slowmatype": 0,
            "signalperiod": 9,
            "signalmatype": 0,
        }
    },
    {"MACDFIX": {"real": "close", "signalperiod": 9}},
    {"MFI": {"high": "high", "low": "low", "close": "close", "volume": "volume", "timeperiod": 30}},
    {"MINUS_DI": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"MINUS_DM": {"high": "high", "low": "low", "timeperiod": 30}},
    {"MOM": {"real": "close", "timeperiod": 30}},
    {"PLUS_DI": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"PLUS_DM": {"high": "high", "low": "low", "timeperiod": 30}},
    {"PPO": {"real": "close", "fastperiod": 12, "slowperiod": 26, "matype": 0}},
    {"ROC": {"real": "close", "timeperiod": 30}},
    {"ROCP": {"real": "close", "timeperiod": 30}},
    {"ROCR": {"real": "close", "timeperiod": 30}},
    {"ROCR100": {"real": "close", "timeperiod": 30}},
    {"RSI": {"real": "close", "timeperiod": 14}},
    {"RSI": {"real": "close", "timeperiod": 30}},
    {
        "STOCH": {
            "high": "high",
            "low": "low",
            "close": "close",
            "fastk_period": 5,
            "slowk_period": 3,
            "slowk_matype": 0,
            "slowd_period": 26,
            "slowd_matype": 0,
        }
    },
    {
        "STOCHF": {
            "high": "high",
            "low": "low",
            "close": "close",
            "fastk_period": 5,
            "fastd_period": 3,
            "fastd_matype": 0,
        }
    },
    {"STOCHRSI": {"real": "close", "timeperiod": 30, "fastk_period": 5, "fastd_period": 3, "fastd_matype": 0}},
    {"TRIX": {"real": "close", "timeperiod": 30}},
    {
        "ULTOSC": {
            "high": "high",
            "low": "low",
            "close": "close",
            "timeperiod1": 7,
            "timeperiod2": 14,
            "timeperiod3": 28,
        }
    },
    {"WILLR": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"BBANDS": {"real": "close", "timeperiod": 30, "nbdevup": 2, "nbdevdn": 2, "matype": 0}},
    {"DEMA": {"real": "close", "timeperiod": 30}},
    {"EMA": {"real": "close", "timeperiod": 14}},
    {"EMA": {"real": "close", "timeperiod": 30}},
    {"EMA": {"real": "close", "timeperiod": 50}},
    {"EMA": {"real": "close", "timeperiod": 100}},
    {"EMA": {"real": "close", "timeperiod": 200}},
    {"HT_TRENDLINE": {"real": "close"}},
    {"KAMA": {"real": "close", "timeperiod": 30}},
    #  {'MA': {'real': 'close', 'timeperiod': 30, 'matype': 0}},
    #  {'MAMA': {'real': 'close', 'fastlimit': 0, 'slowlimit': 0}},
    #  {'MAVP': {'real': 'close',
    #    'periods': array([50.]),
    #    'minperiod': 2,
    #    'maxperiod': 30,
    #    'matype': 0}},
    {"MIDPOINT": {"real": "close", "timeperiod": 30}},
    {"MIDPRICE": {"high": "high", "low": "low", "timeperiod": 30}},
    {"SAR": {"high": "high", "low": "low", "acceleration": 0, "maximum": 0}},
    {
        "SAREXT": {
            "high": "high",
            "low": "low",
            "startvalue": 0,
            "offsetonreverse": 0,
            "accelerationinitlong": 0,
            "accelerationlong": 0,
            "accelerationmaxlong": 0,
            "accelerationinitshort": 0,
            "accelerationshort": 0,
            "accelerationmaxshort": 0,
        }
    },
    {"SMA": {"real": "close", "timeperiod": 14}},
    {"SMA": {"real": "close", "timeperiod": 30}},
    {"SMA": {"real": "close", "timeperiod": 50}},
    {"SMA": {"real": "close", "timeperiod": 100}},
    {"SMA": {"real": "close", "timeperiod": 200}},
    {"T3": {"real": "close", "timeperiod": 30, "vfactor": 0}},
    {"TEMA": {"real": "close", "timeperiod": 30}},
    {"TRIMA": {"real": "close", "timeperiod": 30}},
    {"WMA": {"real": "close", "timeperiod": 14}},
    {"WMA": {"real": "close", "timeperiod": 30}},
    {"WMA": {"real": "close", "timeperiod": 50}},
    {"WMA": {"real": "close", "timeperiod": 100}},
    {"WMA": {"real": "close", "timeperiod": 200}},
    {"CDL2CROWS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDL3BLACKCROWS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDL3INSIDE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDL3LINESTRIKE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDL3OUTSIDE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDL3STARSINSOUTH": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDL3WHITESOLDIERS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLABANDONEDBABY": {"open": "open", "high": "high", "low": "low", "close": "close", "penetration": 0}},
    {"CDLADVANCEBLOCK": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLBELTHOLD": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLBREAKAWAY": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLCLOSINGMARUBOZU": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLCONCEALBABYSWALL": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLCOUNTERATTACK": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLDARKCLOUDCOVER": {"open": "open", "high": "high", "low": "low", "close": "close", "penetration": 0}},
    {"CDLDOJI": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLDOJISTAR": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLDRAGONFLYDOJI": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLENGULFING": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLEVENINGDOJISTAR": {"open": "open", "high": "high", "low": "low", "close": "close", "penetration": 0}},
    {"CDLEVENINGSTAR": {"open": "open", "high": "high", "low": "low", "close": "close", "penetration": 0}},
    {"CDLGAPSIDESIDEWHITE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLGRAVESTONEDOJI": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHAMMER": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHANGINGMAN": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHARAMI": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHARAMICROSS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHIGHWAVE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHIKKAKE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHIKKAKEMOD": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLHOMINGPIGEON": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLIDENTICAL3CROWS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLINNECK": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLINVERTEDHAMMER": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLKICKING": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLKICKINGBYLENGTH": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLLADDERBOTTOM": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLLONGLEGGEDDOJI": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLLONGLINE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLMARUBOZU": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLMATCHINGLOW": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLMATHOLD": {"open": "open", "high": "high", "low": "low", "close": "close", "penetration": 0}},
    {"CDLMORNINGDOJISTAR": {"open": "open", "high": "high", "low": "low", "close": "close", "penetration": 0}},
    {"CDLMORNINGSTAR": {"open": "open", "high": "high", "low": "low", "close": "close", "penetration": 0}},
    {"CDLONNECK": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLPIERCING": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLRICKSHAWMAN": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLRISEFALL3METHODS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLSEPARATINGLINES": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLSHOOTINGSTAR": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLSHORTLINE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLSPINNINGTOP": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLSTALLEDPATTERN": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLSTICKSANDWICH": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLTAKURI": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLTASUKIGAP": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLTHRUSTING": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLTRISTAR": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLUNIQUE3RIVER": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLUPSIDEGAP2CROWS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"CDLXSIDEGAP3METHODS": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"AVGPRICE": {"open": "open", "high": "high", "low": "low", "close": "close"}},
    {"MEDPRICE": {"high": "high", "low": "low"}},
    {"TYPPRICE": {"high": "high", "low": "low", "close": "close"}},
    {"WCLPRICE": {"high": "high", "low": "low", "close": "close"}},
    {"LINEARREG": {"real": "close", "timeperiod": 20}},
    {"LINEARREG": {"real": "close", "timeperiod": 50}},
    {"LINEARREG": {"real": "close", "timeperiod": 100}},
    {"LINEARREG": {"real": "close", "timeperiod": 200}},
    {"LINEARREG": {"real": "close", "timeperiod": 400}},
    # {"LINEARREG_ANGLE": {"real": "close", "timeperiod": 30}},
    # {"LINEARREG_INTERCEPT": {"real": "close", "timeperiod": 30}},
    {"LINEARREG_SLOPE": {"real": "close", "timeperiod": 20}},
    {"LINEARREG_SLOPE": {"real": "close", "timeperiod": 50}},
    {"LINEARREG_SLOPE": {"real": "close", "timeperiod": 100}},
    {"LINEARREG_SLOPE": {"real": "close", "timeperiod": 200}},
    {"LINEARREG_SLOPE": {"real": "close", "timeperiod": 400}},
    {"STDDEV": {"real": "close", "timeperiod": 20, "nbdev": 1}},
    {"STDDEV": {"real": "close", "timeperiod": 50, "nbdev": 1}},
    {"STDDEV": {"real": "close", "timeperiod": 100, "nbdev": 1}},
    {"STDDEV": {"real": "close", "timeperiod": 200, "nbdev": 1}},
    {"STDDEV": {"real": "close", "timeperiod": 400, "nbdev": 1}},
    {"TSF": {"real": "close", "timeperiod": 30}},
    {"VAR": {"real": "close", "timeperiod": 30, "nbdev": 1}},
    {"ATR": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"NATR": {"high": "high", "low": "low", "close": "close", "timeperiod": 30}},
    {"TRANGE": {"high": "high", "low": "low", "close": "close"}},
    {"AD": {"high": "high", "low": "low", "close": "close", "volume": "volume"}},
    {"ADOSC": {"high": "high", "low": "low", "close": "close", "volume": "volume", "fastperiod": 12, "slowperiod": 26}},
    {"OBV": {"real": "close", "volume": "volume"}},
]

# Indicators derived from the TA-Lib indicators
custom_ta_sets__ma_ratio = [
    {
        "output": "SMA_RATIO_14_30",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_14", "col2": "SMA_30"},
    },
    {
        "output": "SMA_RATIO_14_50",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_14", "col2": "SMA_50"},
    },
    {
        "output": "SMA_RATIO_14_100",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_14", "col2": "SMA_100"},
    },
    {
        "output": "SMA_RATIO_14_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_14", "col2": "SMA_200"},
    },
    {
        "output": "SMA_RATIO_30_50",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_30", "col2": "SMA_50"},
    },
    {
        "output": "SMA_RATIO_30_100",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_30", "col2": "SMA_100"},
    },
    {
        "output": "SMA_RATIO_30_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_30", "col2": "SMA_200"},
    },
    {
        "output": "SMA_RATIO_50_100",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_50", "col2": "SMA_100"},
    },
    {
        "output": "SMA_RATIO_50_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_50", "col2": "SMA_200"},
    },
    {
        "output": "SMA_RATIO_100_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "SMA_100", "col2": "SMA_200"},
    },
    {
        "output": "EMA_RATIO_14_30",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_14", "col2": "EMA_30"},
    },
    {
        "output": "EMA_RATIO_14_50",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_14", "col2": "EMA_50"},
    },
    {
        "output": "EMA_RATIO_14_100",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_14", "col2": "EMA_100"},
    },
    {
        "output": "EMA_RATIO_14_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_14", "col2": "EMA_200"},
    },
    {
        "output": "EMA_RATIO_30_50",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_30", "col2": "EMA_50"},
    },
    {
        "output": "EMA_RATIO_30_100",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_30", "col2": "EMA_100"},
    },
    {
        "output": "EMA_RATIO_30_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_30", "col2": "EMA_200"},
    },
    {
        "output": "EMA_RATIO_50_100",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_50", "col2": "EMA_100"},
    },
    {
        "output": "EMA_RATIO_50_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_50", "col2": "EMA_200"},
    },
    {
        "output": "EMA_RATIO_100_200",
        "func": lambda col1, col2: col1 / col2,
        "columns": {"col1": "EMA_100", "col2": "EMA_200"},
    },
    {
        "output": "LINEARREG_20_ZSCORE",
        "func": lambda col1, col2, col3: (col1 - col2) / col3,
        "columns": {"col1": "Close", "col2": "LINEARREG_20", "col3": "STDDEV_20_1"},
    },
    {
        "output": "LINEARREG_50_ZSCORE",
        "func": lambda col1, col2, col3: (col1 - col2) / col3,
        "columns": {"col1": "Close", "col2": "LINEARREG_50", "col3": "STDDEV_50_1"},
    },
    {
        "output": "LINEARREG_100_ZSCORE",
        "func": lambda col1, col2, col3: (col1 - col2) / col3,
        "columns": {"col1": "Close", "col2": "LINEARREG_100", "col3": "STDDEV_100_1"},
    },
    {
        "output": "LINEARREG_200_ZSCORE",
        "func": lambda col1, col2, col3: (col1 - col2) / col3,
        "columns": {"col1": "Close", "col2": "LINEARREG_200", "col3": "STDDEV_200_1"},
    },
    {
        "output": "LINEARREG_400_ZSCORE",
        "func": lambda col1, col2, col3: (col1 - col2) / col3,
        "columns": {"col1": "Close", "col2": "LINEARREG_400", "col3": "STDDEV_400_1"},
    },
]

# Indicators derived from the raw price data
custom_ta_sets__regression_channel = [
    {"output": "CHANNEL_CLOSE_VS_LINE", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "Close", "col2": "line_end_y"}},
    {"output": "CHANNEL_CLOSE_VS_MINUS", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "Close", "col2": "line_minus_end_y"}},
    {"output": "CHANNEL_CLOSE_VS_PLUS", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "Close", "col2": "line_plus_end_y"}},
    {"output": "CHANNEL_LOW_VS_LINE", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "Low", "col2": "line_end_y"}},
    {"output": "CHANNEL_LOW_VS_MINUS", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "Low", "col2": "line_minus_end_y"}},
    {"output": "CHANNEL_LOW_VS_PLUS", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "Low", "col2": "line_plus_end_y"}},
    {"output": "CHANNEL_HIGH_VS_LINE", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "High", "col2": "line_end_y"}},
    {"output": "CHANNEL_HIGH_VS_MINUS", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "High", "col2": "line_minus_end_y"}},
    {"output": "CHANNEL_HIGH_VS_PLUS", "func": lambda col1, col2: col1 / col2, "columns": {"col1": "High", "col2": "line_plus_end_y"}},
]

# Indicators derived from the raw price data
custom_ta_sets__regression_channel_ma = [
    {
        "output": "CHANNEL_CLOSE_VS_MINUS_MA5",
        "func": lambda col1: col1.rolling(window=5).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_MINUS"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_MINUS_MA10",
        "func": lambda col1: col1.rolling(window=10).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_MINUS"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_MINUS_MA15",
        "func": lambda col1: col1.rolling(window=15).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_MINUS"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_LINE_MA5",
        "func": lambda col1: col1.rolling(window=5).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_LINE"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_LINE_MA10",
        "func": lambda col1: col1.rolling(window=10).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_LINE"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_LINE_MA15",
        "func": lambda col1: col1.rolling(window=15).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_LINE"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_PLUS_MA5",
        "func": lambda col1: col1.rolling(window=5).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_PLUS"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_PLUS_MA10",
        "func": lambda col1: col1.rolling(window=10).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_PLUS"},
    },
    {
        "output": "CHANNEL_CLOSE_VS_PLUS_MA15",
        "func": lambda col1: col1.rolling(window=15).mean(),
        "columns": {"col1": "CHANNEL_CLOSE_VS_PLUS"},
    },
]

# Indicators derived from the raw price data
custom_ta_sets__change_ratio = [
    {"output": "CHANGE_CLOSE_5", "func": lambda col1: col1 / col1.shift(5), "columns": {"col1": "Close"}},
    {"output": "CHANGE_CLOSE_10", "func": lambda col1: col1 / col1.shift(10), "columns": {"col1": "Close"}},
    {"output": "CHANGE_CLOSE_20", "func": lambda col1: col1 / col1.shift(20), "columns": {"col1": "Close"}},
    {"output": "CHANGE_CLOSE_30", "func": lambda col1: col1 / col1.shift(30), "columns": {"col1": "Close"}},
    {"output": "CHANGE_CLOSE_50", "func": lambda col1: col1 / col1.shift(50), "columns": {"col1": "Close"}},
    {"output": "CHANGE_CLOSE_100", "func": lambda col1: col1 / col1.shift(100), "columns": {"col1": "Close"}},
    {"output": "CHANGE_CLOSE_200", "func": lambda col1: col1 / col1.shift(200), "columns": {"col1": "Close"}},
]

# Calculations of future price movements from the raw price data
custom_ta_sets__future = [
    {"output": "FUTURE_END_CLOSE_5", "func": lambda col1: col1.shift(-5) / col1, "columns": {"col1": "Close"}},
    {"output": "FUTURE_END_CLOSE_10", "func": lambda col1: col1.shift(-10) / col1, "columns": {"col1": "Close"}},
    {"output": "FUTURE_END_CLOSE_15", "func": lambda col1: col1.shift(-15) / col1, "columns": {"col1": "Close"}},
    {"output": "FUTURE_END_CLOSE_20", "func": lambda col1: col1.shift(-20) / col1, "columns": {"col1": "Close"}},
    {"output": "FUTURE_END_CLOSE_30", "func": lambda col1: col1.shift(-30) / col1, "columns": {"col1": "Close"}},
    {"output": "FUTURE_END_CLOSE_50", "func": lambda col1: col1.shift(-50) / col1, "columns": {"col1": "Close"}},
    {
        "output": "FUTURE_MAX_CLOSE_5",
        "func": lambda col1: (col1[::-1].shift(1).rolling(window=5).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close"},
    },
    {
        "output": "FUTURE_MAX_CLOSE_10",
        "func": lambda col1: (col1[::-1].shift(1).rolling(window=10).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close"},
    },
    {
        "output": "FUTURE_MAX_CLOSE_15",
        "func": lambda col1: (col1[::-1].shift(1).rolling(window=15).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close"},
    },
    {
        "output": "FUTURE_MAX_CLOSE_20",
        "func": lambda col1: (col1[::-1].shift(1).rolling(window=20).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close"},
    },
    {
        "output": "FUTURE_MAX_CLOSE_30",
        "func": lambda col1: (col1[::-1].shift(1).rolling(window=30).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close"},
    },
    {
        "output": "FUTURE_MAX_CLOSE_50",
        "func": lambda col1: (col1[::-1].shift(1).rolling(window=50).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close"},
    },
    {
        "output": "FUTURE_MAX_HIGH_5",
        "func": lambda col1, col2: (col2[::-1].shift(1).rolling(window=5).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close", "col2": "High"},
    },
    {
        "output": "FUTURE_MAX_HIGH_10",
        "func": lambda col1, col2: (col2[::-1].shift(1).rolling(window=10).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close", "col2": "High"},
    },
    {
        "output": "FUTURE_MAX_HIGH_15",
        "func": lambda col1, col2: (col2[::-1].shift(1).rolling(window=15).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close", "col2": "High"},
    },
    {
        "output": "FUTURE_MAX_HIGH_20",
        "func": lambda col1, col2: (col2[::-1].shift(1).rolling(window=20).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close", "col2": "High"},
    },
    {
        "output": "FUTURE_MAX_HIGH_30",
        "func": lambda col1, col2: (col2[::-1].shift(1).rolling(window=30).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close", "col2": "High"},
    },
    {
        "output": "FUTURE_MAX_HIGH_50",
        "func": lambda col1, col2: (col2[::-1].shift(1).rolling(window=50).max() / col1[::-1])[::-1],
        "columns": {"col1": "Close", "col2": "High"},
    },
]


pattern_columns = [
    "CDL2CROWS",
    "CDL3BLACKCROWS",
    "CDL3INSIDE",
    "CDL3LINESTRIKE",
    "CDL3OUTSIDE",
    "CDL3STARSINSOUTH",
    "CDL3WHITESOLDIERS",
    "CDLABANDONEDBABY",
    "CDLADVANCEBLOCK",
    "CDLBELTHOLD",
    "CDLBREAKAWAY",
    "CDLCLOSINGMARUBOZU",
    "CDLCONCEALBABYSWALL",
    "CDLCOUNTERATTACK",
    "CDLDARKCLOUDCOVER",
    "CDLDOJI",
    "CDLDOJISTAR",
    "CDLDRAGONFLYDOJI",
    "CDLENGULFING",
    "CDLEVENINGDOJISTAR",
    "CDLEVENINGSTAR",
    "CDLGAPSIDESIDEWHITE",
    "CDLGRAVESTONEDOJI",
    "CDLHAMMER",
    "CDLHANGINGMAN",
    "CDLHARAMI",
    "CDLHARAMICROSS",
    "CDLHIGHWAVE",
    "CDLHIKKAKE",
    "CDLHIKKAKEMOD",
    "CDLHOMINGPIGEON",
    "CDLIDENTICAL3CROWS",
    "CDLINNECK",
    "CDLINVERTEDHAMMER",
    "CDLKICKING",
    "CDLKICKINGBYLENGTH",
    "CDLLADDERBOTTOM",
    "CDLLONGLEGGEDDOJI",
    "CDLLONGLINE",
    "CDLMARUBOZU",
    "CDLMATCHINGLOW",
    "CDLMATHOLD",
    "CDLMORNINGDOJISTAR",
    "CDLMORNINGSTAR",
    "CDLONNECK",
    "CDLPIERCING",
    "CDLRICKSHAWMAN",
    "CDLRISEFALL3METHODS",
    "CDLSEPARATINGLINES",
    "CDLSHOOTINGSTAR",
    "CDLSHORTLINE",
    "CDLSPINNINGTOP",
    "CDLSTALLEDPATTERN",
    "CDLSTICKSANDWICH",
    "CDLTAKURI",
    "CDLTASUKIGAP",
    "CDLTHRUSTING",
    "CDLTRISTAR",
    "CDLUNIQUE3RIVER",
    "CDLUPSIDEGAP2CROWS",
    "CDLXSIDEGAP3METHODS",
]
